#ifndef TEXTURE_TYPE_HPP
#define TEXTURE_TYPE_HPP

enum class TextureType
{
    NONE,
    ROCK,
    WATER,
    BACKGROUND,
    AIRSTRIKE_TARGET,
    PLAYER_SUPERMAN,
    PLAYER_HULK,
    PLAYER_IRONMAN,
    WEAPON_AIRSTRIKE,
    WEAPON_GRENADE,
    WEAPON_SHOTGUN,
    WEAPON_SNIPER,
    WEAPON_SUPERMAN,
    WEAPON_IRONMAN,
    WEAPON_HULK,
    BULLET,
};

#endif